### ISSUE TITLE
wcorg-login-message.phpを入れたときにログイン画面でNoticeエラーが出る

### ISSUE THREAD

**Issue by gouten5010** [wcosaka2018/wc-vccw#1]
### How to
```
$ git checkout wcorg-login-message
$ vagrnat up
```

### ScreenShot
<img width="475" alt="2018-03-01 1 12 34" src="https://user-images.githubusercontent.com/3461188/36798342-b663ae84-1ced-11e8-918c-6f30e420a720.png">

### Error
```
Notice: Trying to get property of non-object in /var/www/html/wp-content/mu-plugins/wcorg-login-message.php on line 133
```

**Comment by torounit** [comment]
https://meta.trac.wordpress.org/browser/sites/trunk/wordcamp.org/public_html/wp-content/mu-plugins/wcorg-login-message.php#L133

この行でエラーですね。

$blog_details->blog_id の blog_id が無いと言うことで、

https://meta.trac.wordpress.org/browser/sites/trunk/wordcamp.org/public_html/wp-content/mu-plugins/wcorg-login-message.php#L131

が怪しいデスね。

**Comment by gouten5010** [comment]
修正してくれたコードでいけた。ありがとう！
